######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 11 11:09:55 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sak.h qapplicationargb.h
SOURCES += main.cpp sak.cpp qapplicationargb.cpp

contains(CONFIG, vale) {
	RESOURCES += sak.vale.qrc
} else {
	RESOURCES += sak.qrc
}