######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 20 11:41:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /tmp/gmailsender/. .

QT+=network

# Input
HEADERS += mailsender.h
SOURCES += mailsender.cpp main.cpp
